#!/usr/bin/env python3
"""
server_librarian.py
  --summary (default): 当日ログをLLMで要約し latest_summary.md に保存
  --ingest           : obsidian_logs を読み込み data/knowledge_base/wiki/ を更新
"""
import argparse
import json
import os
import re
import requests
from datetime import datetime, timezone
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent / ".env")

PROJECT_ROOT = Path(__file__).parent
OLLAMA_URL   = os.getenv("OLLAMA_ENDPOINT", "http://localhost:11434") + "/api/generate"
OLLAMA_MODEL = "llama3.1:latest"
OUTPUT_FILE  = PROJECT_ROOT / "latest_summary.md"
WIKI_ROOT    = PROJECT_ROOT / "data" / "knowledge_base" / "wiki"
LOG_DIR      = PROJECT_ROOT / "data" / "knowledge_base" / "obsidian_logs"
TODAY        = datetime.now().strftime("%Y-%m-%d")
NOW          = datetime.now().strftime("%Y-%m-%d %H:%M")


# ─────────────────────────────────────────────
# LLM ユーティリティ
# ─────────────────────────────────────────────

def call_gemini(prompt: str) -> str:
    """Gemini 経由でLLM呼び出し（Google API Key が必要）。

    モデル名は直書きせず llm_factory から取る（.env の GEMINI_MODEL が唯一の指定箇所）。
    """
    from skills.llm_factory import get_gemini_model
    api_key = os.getenv("GOOGLE_API_KEY", "")
    if not api_key:
        return ""
    model = get_gemini_model()
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
    payload = {"contents": [{"parts": [{"text": prompt}]}]}
    try:
        resp = requests.post(url, json=payload, timeout=60)
        resp.raise_for_status()
        return resp.json()["candidates"][0]["content"]["parts"][0]["text"].strip()
    except Exception:
        return ""


def call_ollama(prompt: str) -> str:
    payload = {"model": OLLAMA_MODEL, "prompt": prompt, "stream": False}
    try:
        resp = requests.post(OLLAMA_URL, json=payload, timeout=300)
        resp.raise_for_status()
        return resp.json().get("response", "").strip()
    except requests.exceptions.ConnectionError:
        return "[ERROR] Ollama に接続できませんでした。"
    except requests.exceptions.Timeout:
        return "[ERROR] Ollama がタイムアウトしました。"
    except Exception as e:
        return f"[ERROR] {e}"


def call_llm(prompt: str) -> str:
    """Gemini 優先、失敗時は Ollama フォールバック。"""
    result = call_gemini(prompt)
    if result and not result.startswith("[ERROR]"):
        return result
    return call_ollama(prompt)


# ─────────────────────────────────────────────
# --summary モード（既存機能）
# ─────────────────────────────────────────────

def read_latest_file(directory: Path, pattern: str) -> str:
    files = sorted(directory.glob(pattern), key=os.path.getmtime, reverse=True)
    return files[0].read_text(encoding="utf-8") if files else ""


def read_todays_obsidian_logs() -> str:
    date_tag = datetime.now().strftime("%Y%m%d")
    files = sorted(LOG_DIR.glob(f"Log_{date_tag}_*.md"), key=os.path.getmtime)
    return "\n\n---\n\n".join(f.read_text(encoding="utf-8") for f in files)


def read_portfolio() -> str:
    p = PROJECT_ROOT / "data" / "portfolio.json"
    return p.read_text(encoding="utf-8") if p.exists() else ""


def run_summary():
    print(f"[server_librarian:summary] {TODAY} のログを収集中...")
    screener   = read_latest_file(PROJECT_ROOT / "data" / "screener", "*.json")
    trade_logs = read_todays_obsidian_logs()
    portfolio  = read_portfolio()
    bbs        = read_latest_file(PROJECT_ROOT / "bbs", "*.json")

    sections = []
    if screener:
        sections.append(f"## スクリーニング結果 (Top3候補)\n```json\n{screener}\n```")
    if trade_logs:
        sections.append(f"## 本日の売買ログ\n{trade_logs}")
    if portfolio:
        sections.append(f"## 現在のポートフォリオ\n```json\n{portfolio}\n```")
    if bbs:
        sections.append(f"## セッションログ (BBS)\n{bbs[:2000]}")

    if not sections:
        msg = f"[{TODAY}] ログが見つかりませんでした。"
        OUTPUT_FILE.write_text(msg, encoding="utf-8")
        print(msg)
        return

    log_body = "\n\n".join(sections)
    prompt = f"""あなたは投資AIシステム「ai-investor-bot」の開発・運用を支援するアナリストです。
以下は {TODAY} の自動トレードシステムの実行ログです。
これをObsidianの日報として読みやすくMarkdown形式で要約してください。

要約に含めるべき内容:
1. 本日のTop3スクリーニング候補銘柄とその選定理由（RSI・出来高・MA乖離）
2. 実際に行われた売買アクション（Buy/Sell）と損益結果
3. 各AIエージェントの推論プロセスのポイント（CoT要約）
4. 現在の保有ポジションサマリー
5. 明日以降への気づき・注意点（あれば）

出力形式: そのままObsidianに貼り付けられるMarkdown。見出しは ## を使用。

--- ログデータ開始 ---
{log_body}
--- ログデータ終了 ---
"""
    print("[server_librarian:summary] LLM に要約を依頼中...")
    summary = call_llm(prompt)
    output = f"# {TODAY} トレード日報\n\n{summary}\n\n---\n*Generated by server_librarian.py at {datetime.now().strftime('%H:%M:%S')}*\n"
    OUTPUT_FILE.write_text(output, encoding="utf-8")
    print(f"[server_librarian:summary] 完了 → {OUTPUT_FILE}")


# ─────────────────────────────────────────────
# --ingest モード（Wiki更新）
# ─────────────────────────────────────────────

class WikiIngestor:
    """obsidian_logs を読み込み wiki/ 以下を生きたWikiとして更新する。"""

    FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)
    WIKI_LINK_RE   = re.compile(r"\[\[([^\]|]+)(?:\|[^\]]*)?\]\]")

    def __init__(self):
        self.wiki_root = WIKI_ROOT
        self.tickers_dir  = self.wiki_root / "tickers"
        self.concepts_dir = self.wiki_root / "concepts"
        self.log_path     = self.wiki_root / "log.md"
        self.index_path   = self.wiki_root / "INDEX.md"
        for d in (self.tickers_dir, self.concepts_dir):
            d.mkdir(parents=True, exist_ok=True)

    # ── ユーティリティ ──────────────────────────

    def _parse_frontmatter(self, text: str) -> dict:
        m = self.FRONTMATTER_RE.match(text)
        if not m:
            return {}
        result = {}
        for line in m.group(1).splitlines():
            if ":" in line:
                k, _, v = line.partition(":")
                result[k.strip()] = v.strip().strip('"')
        return result

    def _processed_log_names(self) -> set[str]:
        """log.md の INGEST 行から処理済みファイル名（stem）を収集する。"""
        if not self.log_path.exists():
            return set()
        result: set[str] = set()
        for line in self.log_path.read_text(encoding="utf-8").splitlines():
            if "| INGEST |" not in line:
                continue
            m = re.search(r"files=\[([^\]]*)\]", line)
            if m:
                for name in m.group(1).split(","):
                    name = name.strip()
                    if name:
                        result.add(name)
        return result

    def _append_log(self, tickers: list[str], summary: str, log_files: list[str] | None = None):
        self.log_path.parent.mkdir(parents=True, exist_ok=True)
        files_part = f"files=[{','.join(log_files)}] | " if log_files else ""
        line = f"{NOW} | INGEST | {','.join(tickers) or 'なし'} | {files_part}{summary}\n"
        with self.log_path.open("a", encoding="utf-8") as f:
            f.write(line)
        print(f"[ingest] log.md に追記: {line.strip()}")

    def _read_ticker_meta(self, ticker: str) -> dict:
        """knowledge_base/{TICKER}.json から基本情報を取得。"""
        p = PROJECT_ROOT / "data" / "knowledge_base" / f"{ticker}.json"
        if not p.exists():
            return {}
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
            meta = data.get("metadata", {})
            return {
                "name":   meta.get("name", ticker),
                "sector": meta.get("sector", ""),
            }
        except Exception:
            return {}

    # ── ティッカーページ更新 ────────────────────

    def update_ticker_page(self, ticker: str, trade: dict):
        path = self.tickers_dir / f"{ticker}.md"
        meta = self._read_ticker_meta(ticker)
        name   = meta.get("name", ticker)
        sector = meta.get("sector", "")

        action      = trade.get("action", "")
        date        = trade.get("date", TODAY)
        profit_loss = trade.get("profit_loss", "")
        score       = trade.get("score", "")
        log_ref     = trade.get("log_ref", "")
        price       = trade.get("price", "")
        assessment  = trade.get("assessment", action)  # BUY→WATCH, SELL→HOLD など

        # 既存ページ読み込み
        if path.exists():
            existing = path.read_text(encoding="utf-8")
        else:
            existing = self._new_ticker_page(ticker, name, sector)

        # トレード履歴テーブルに行を追加（count=1 で先頭1件のみ置換し重複防止）
        row = f"| {date} | {action} | {price} | {score} | {profit_loss} | [[{log_ref}]] |"
        HEADER = "| 日付 | アクション | 価格 | スコア | 結果 | ログ |\n|---|---|---|---|---|---|\n"
        if HEADER in existing:
            existing = existing.replace(HEADER, f"{HEADER}{row}\n", 1)
        else:
            existing += f"\n## トレード履歴\n{HEADER}{row}\n"

        # 評価変遷に追記（count=1 で重複防止）
        evolution_line = f"- {date}: {assessment} (score={score}, P&L={profit_loss})"
        EVOL_HEADER = "## 評価変遷\n"
        if EVOL_HEADER in existing:
            existing = existing.replace(EVOL_HEADER, f"{EVOL_HEADER}{evolution_line}\n", 1)
        else:
            existing += f"\n{EVOL_HEADER}{evolution_line}\n"

        # frontmatter の assessment と last_updated を更新
        existing = re.sub(r"^assessment: .*$", f"assessment: {assessment}", existing, flags=re.MULTILINE)
        existing = re.sub(r"^last_updated: .*$", f"last_updated: {TODAY}", existing, flags=re.MULTILINE)

        path.write_text(existing, encoding="utf-8")
        print(f"[ingest] tickers/{ticker}.md 更新完了")

    def _new_ticker_page(self, ticker: str, name: str, sector: str) -> str:
        return f"""---
ticker: {ticker}
name: {name}
sector: {sector}
last_updated: {TODAY}
assessment: WATCH
assessment_score: 0.0
---

# [[tickers/{ticker}|{ticker}]] — {name}

## 概要

- セクター: {sector}
- 銘柄コード: {ticker}

## トレード履歴

| 日付 | アクション | 価格 | スコア | 結果 | ログ |
|---|---|---|---|---|---|

## 評価変遷

## 関連コンセプト

## 関連ニュース（最新3件）
"""

    # ── コンセプト抽出・更新 ────────────────────

    def extract_and_update_concepts(self, ticker: str, log_text: str, trade: dict):
        """LLMにコンセプトを抽出させ、concepts/ を更新する。"""
        action = trade.get("action", "")
        result = trade.get("profit_loss", "")
        date   = trade.get("date", TODAY)

        prompt = f"""以下はトレードログです。このトレードで観察された投資コンセプト（MACD、RSI、SNS煽り、利確戦略など）を
1～3個抽出してください。各コンセプトについて以下の形式でJSONリストを返してください:
[{{"concept": "snake_case_name", "title": "日本語タイトル", "description": "1行説明", "outcome": "成功/失敗/中立"}}]

ログ:
{log_text[:1500]}
"""
        raw = call_llm(prompt)
        # JSONブロックの抽出
        m = re.search(r"\[.*\]", raw, re.DOTALL)
        if not m:
            return
        try:
            concepts = json.loads(m.group(0))
        except json.JSONDecodeError:
            return

        updated_concepts = []
        for c in concepts:
            name = re.sub(r"[^a-z0-9_]", "", c.get("concept", "").lower().replace(" ", "_"))
            if not name:
                continue
            title       = c.get("title", name)
            description = c.get("description", "")
            outcome     = c.get("outcome", "中立")
            self._update_concept_page(name, title, description, ticker, date, outcome)
            updated_concepts.append(name)
            # ティッカーページに関連コンセプトリンクを追記
            self._link_concept_to_ticker(ticker, name, title)

        return updated_concepts

    def _update_concept_page(self, concept: str, title: str, description: str,
                              ticker: str, date: str, outcome: str):
        path = self.concepts_dir / f"{concept}.md"
        row  = f"| {date} | [[tickers/{ticker}]] | {outcome} | |"

        if path.exists():
            existing = path.read_text(encoding="utf-8")
            # 観測事例テーブルに行追加（count=1 で重複防止）
            CHEADER = "| 日付 | 銘柄 | 結果 | 備考 |\n|---|---|---|---|\n"
            existing = existing.replace(CHEADER, f"{CHEADER}{row}\n", 1)
            # linked_tickers を更新
            existing = re.sub(
                r"^linked_tickers: \[([^\]]*)\]",
                lambda m2: f"linked_tickers: [{', '.join(sorted(set(m2.group(1).split(', ') + [ticker])))}]",
                existing,
                flags=re.MULTILINE,
            )
            existing = re.sub(r"^last_updated: .*$", f"last_updated: {TODAY}", existing, flags=re.MULTILINE)
            path.write_text(existing, encoding="utf-8")
        else:
            content = f"""---
concept: {concept}
title: {title}
last_updated: {TODAY}
linked_tickers: [{ticker}]
---

# [[concepts/{concept}|{title}]]

## 定義

{description}

## 観測事例

| 日付 | 銘柄 | 結果 | 備考 |
|---|---|---|---|
{row}

## 教訓

（事例が蓄積されると帰納的なまとめを追記する）
"""
            path.write_text(content, encoding="utf-8")
        print(f"[ingest] concepts/{concept}.md 更新完了")

    def _link_concept_to_ticker(self, ticker: str, concept: str, title: str):
        path = self.tickers_dir / f"{ticker}.md"
        if not path.exists():
            return
        existing = path.read_text(encoding="utf-8")
        link_line = f"- [[concepts/{concept}]] — {title}"
        if link_line in existing:
            return
        if "## 関連コンセプト" in existing:
            existing = existing.replace("## 関連コンセプト\n", f"## 関連コンセプト\n{link_line}\n", 1)
            path.write_text(existing, encoding="utf-8")

    # ── INDEX.md 再生成 ─────────────────────────

    def rebuild_index(self):
        # ティッカーページ一覧
        ticker_lines = []
        for p in sorted(self.tickers_dir.glob("*.md")):
            fm = self._parse_frontmatter(p.read_text(encoding="utf-8"))
            t  = fm.get("ticker", p.stem)
            name = fm.get("name", t)
            assessment = fm.get("assessment", "—")
            last_updated = fm.get("last_updated", "")
            ticker_lines.append(f"- [[tickers/{p.stem}]] — {name} | {assessment} | {last_updated}")

        # コンセプトページ一覧
        concept_lines = []
        for p in sorted(self.concepts_dir.glob("*.md")):
            fm = self._parse_frontmatter(p.read_text(encoding="utf-8"))
            title = fm.get("title", p.stem)
            concept_lines.append(f"- [[concepts/{p.stem}]] — {title}")

        # 最近のIngest履歴（最新5件）
        log_lines = []
        if self.log_path.exists():
            all_lines = [l for l in self.log_path.read_text(encoding="utf-8").splitlines() if l.strip()]
            log_lines = all_lines[-5:]

        # ポートフォリオ
        portfolio_section = ""
        pf_path = PROJECT_ROOT / "data" / "portfolio.json"
        if pf_path.exists():
            try:
                pf = json.loads(pf_path.read_text(encoding="utf-8"))
                positions = pf.get("positions", [])
                if positions:
                    rows = ["| 銘柄 | 購入日 | 購入単価 | 株数 | ステータス |",
                            "|---|---|---|---|---|"]
                    for pos in positions:
                        rows.append(
                            f"| [[tickers/{pos.get('ticker','?')}]] "
                            f"| {pos.get('buy_date','')} "
                            f"| ${pos.get('buy_price',0):.2f} "
                            f"| {pos.get('shares',0)} "
                            f"| {pos.get('status','')} |"
                        )
                    portfolio_section = "\n".join(rows)
                else:
                    portfolio_section = "現在、保有ポジションはありません。"
            except Exception:
                portfolio_section = "（portfolio.json 読み込みエラー）"

        content = f"""# 投資ナレッジベース INDEX

> 最終更新: {NOW}
> 管理スクリプト: `python server_librarian.py --ingest`

## 現在の投資方針

AIエージェントの直近判断をもとに自動生成。詳細は各ティッカーページを参照。

## 保有ポジション

{portfolio_section}

## ティッカー別ページ

{chr(10).join(ticker_lines) if ticker_lines else "（まだページがありません）"}

## コンセプトページ

{chr(10).join(concept_lines) if concept_lines else "（まだページがありません）"}

## 最近の Ingest 履歴

```
{chr(10).join(log_lines) if log_lines else "（まだ履歴がありません）"}
```
"""
        self.index_path.write_text(content, encoding="utf-8")
        print(f"[ingest] INDEX.md 再生成完了")

    # ── メイン Ingest ──────────────────────────

    def run(self):
        processed = self._processed_log_names()
        print(f"[ingest] 処理済みファイル数: {len(processed)}件。未処理ログを確認します")

        # 処理済みファイル名で除外（mtime/時刻に依存しない）
        all_logs = sorted(LOG_DIR.glob("Log_*.md"), key=lambda p: p.name)
        new_logs = [p for p in all_logs if p.stem not in processed]

        if not new_logs:
            print("[ingest] 新規ログなし。Ingestをスキップします。")
            return

        print(f"[ingest] {len(new_logs)} 件の新規ログを処理します")

        processed_tickers = []
        updated_summaries = []

        for log_path in new_logs:
            text = log_path.read_text(encoding="utf-8")
            fm   = self._parse_frontmatter(text)
            ticker = fm.get("ticker", "")
            action = fm.get("action", "")
            date   = fm.get("date", TODAY)
            pl     = fm.get("profit_loss", "")

            if not ticker:
                continue

            # アクションからassessmentを推定
            if action == "BUY":
                assessment = "BUY"
            elif action == "SELL":
                outcome = fm.get("outcome", "")
                assessment = "HOLD" if outcome == "CLOSED" else "SELL"
            else:
                assessment = "WATCH"

            trade = {
                "action":      action,
                "date":        date,
                "profit_loss": pl,
                "assessment":  assessment,
                "log_ref":     log_path.stem,
            }
            self.update_ticker_page(ticker, trade)
            concepts = self.extract_and_update_concepts(ticker, text, trade)
            processed_tickers.append(ticker)

            concept_str = ",".join(concepts) if concepts else "なし"
            updated_summaries.append(f"tickers/{ticker}更新 concepts=[{concept_str}]")

        self.rebuild_index()

        summary = " | ".join(updated_summaries) if updated_summaries else "変更なし"
        self._append_log(
            list(dict.fromkeys(processed_tickers)),
            f"INDEX再生成 | {summary}",
            log_files=[p.stem for p in new_logs],
        )
        print(f"[ingest] 完了。処理銘柄: {set(processed_tickers)}")


# ─────────────────────────────────────────────
# エントリポイント
# ─────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="server_librarian — ログ管理ツール")
    parser.add_argument("--ingest",   action="store_true", help="obsidian_logs → wiki/ を更新")
    parser.add_argument("--summary",  action="store_true", help="日報を latest_summary.md に生成（デフォルト）")
    args = parser.parse_args()

    if args.ingest:
        WikiIngestor().run()
    else:
        run_summary()


if __name__ == "__main__":
    main()
